[project]
name = "auction-house"
description = "NFT and asset auction system"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
[contracts.auction-house]
path = "contracts/auction-house.clar"
clarity_version = 2
epoch = 2.4
